- name: Update web servers
  hosts: 127.0.0.1

     
  tasks:

  - name: Creating a file with 
    copy:
        dest: "/home/script.py"
        content: |
                  #!/usr/bin/python
                  print ('Hello, world!')
    become: yes              

  - name: Execute script
    command: /home/script.py
    become: yes
            
    

