- name: Update web servers
  hosts: 127.0.0.1

     
  tasks:    
  - name: Creating a file with123
    copy:
        dest: "script.py"
        content: |
                  #!/usr/bin/python
                  print ('Hello, world!')
    become_exe: su

  - name: Changing perm of "/home/script.py", adding "+x"
    file: dest=script.py mode=a+x        

  - name: Execute script
    script: script.py
    register: result
    
  - name: Database details
    debug: 
       msg: result

            
    

