---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.repo-epel

collections:
  - name: community.mysql
  - name: amazon.aws
  - name: community.general
  - name: fmpro12.lowcase
    source: https://github.com/fmpro12/ansible


