---
- name: Update web servers
  hosts: localhost
  tasks:
   - name: Create database user with name 'bob4' and password '12345' with all database privileges
     community.mysql.mysql_user:
          login_host: "{{ host }}"
          name: "{{ username }}"
          password: "{{ password }}" 
          priv: '*.*:{{ permissions }}'
          state: present
