- name: Update web servers
  hosts: 127.0.0.1
  
  tasks:
- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  pip:
    name: pymysql
    state: present

- name: Create database user with name 'bob2' and password '12345' with all database privileges
  community.mysql.mysql_user:
      login_host: 10.42.0.38
      login_user: admin
      login_password: zubur1 
      name: bob2
      password: 12345
      priv: '*.*:ALL'
      state: present
