---
- name: Update web servers
  hosts: "{{ server }}"
  tasks:
   - name: Create database user
     community.mysql.mysql_user:
          login_host: "{{ host }}"
          name: "{{ username }}"
          password: "{{ password }}" 
          priv: '{{ database }}.*:{{ permissions }}'
          state: present
